import {
  Tent,
  House,
  Mountain,
  Store,
  Utensils,
  Hotel,
  Bed,
} from "lucide-react";

export const categories = [
  {
    label: "camping",
    icon: Tent,
  },
  {
    label: "house",
    icon: House,
  },
  {
    label: "hotel",
    icon: Hotel,
  },
  {
    label: "hostel",
    icon: Bed,
  },
  {
    label: "moutain",
    icon: Mountain,
  },
  {
    label: "store",
    icon: Store,
  },
  {
    label: "food",
    icon: Utensils,
  },
];

export const provinces = [
  { PROVINCE_ID: 1, PROVINCE_NAME: "Bangkok" },
  { PROVINCE_ID: 2, PROVINCE_NAME: "Samut Prakan" },
  { PROVINCE_ID: 3, PROVINCE_NAME: "Nonthaburi" },
  { PROVINCE_ID: 4, PROVINCE_NAME: "Pathum Thani" },
  { PROVINCE_ID: 5, PROVINCE_NAME: "Phra Nakhon Si Ayutthaya" },
  { PROVINCE_ID: 6, PROVINCE_NAME: "Ang Thong" },
  { PROVINCE_ID: 7, PROVINCE_NAME: "Lopburi" },
  { PROVINCE_ID: 8, PROVINCE_NAME: "Sing Buri" },
  { PROVINCE_ID: 9, PROVINCE_NAME: "Chai Nat" },
  { PROVINCE_ID: 10, PROVINCE_NAME: "Saraburi" },
  { PROVINCE_ID: 11, PROVINCE_NAME: "Chonburi" },
  { PROVINCE_ID: 12, PROVINCE_NAME: "Rayong" },
  { PROVINCE_ID: 13, PROVINCE_NAME: "Chanthaburi" },
  { PROVINCE_ID: 14, PROVINCE_NAME: "Trat" },
  { PROVINCE_ID: 15, PROVINCE_NAME: "Chachoengsao" },
  { PROVINCE_ID: 16, PROVINCE_NAME: "Prachinburi" },
  { PROVINCE_ID: 17, PROVINCE_NAME: "Nakhon Nayok" },
  { PROVINCE_ID: 18, PROVINCE_NAME: "Sa Kaeo" },
  { PROVINCE_ID: 19, PROVINCE_NAME: "Nakhon Ratchasima" },
  { PROVINCE_ID: 20, PROVINCE_NAME: "Buri Ram" },
  { PROVINCE_ID: 21, PROVINCE_NAME: "Surin" },
  { PROVINCE_ID: 22, PROVINCE_NAME: "Si Sa Ket" },
  { PROVINCE_ID: 23, PROVINCE_NAME: "Ubon Ratchathani" },
  { PROVINCE_ID: 24, PROVINCE_NAME: "Yasothon" },
  { PROVINCE_ID: 25, PROVINCE_NAME: "Chaiyaphum" },
  { PROVINCE_ID: 26, PROVINCE_NAME: "Amnat Charoen" },
  { PROVINCE_ID: 27, PROVINCE_NAME: "Nong Bua Lamphu" },
  { PROVINCE_ID: 28, PROVINCE_NAME: "Khon Kaen" },
  { PROVINCE_ID: 29, PROVINCE_NAME: "Udon Thani" },
  { PROVINCE_ID: 30, PROVINCE_NAME: "Loei" },
  { PROVINCE_ID: 31, PROVINCE_NAME: "Nong Khai" },
  { PROVINCE_ID: 32, PROVINCE_NAME: "Maha Sarakham" },
  { PROVINCE_ID: 33, PROVINCE_NAME: "Roi Et" },
  { PROVINCE_ID: 34, PROVINCE_NAME: "Kalasin" },
  { PROVINCE_ID: 35, PROVINCE_NAME: "Sakon Nakhon" },
  { PROVINCE_ID: 36, PROVINCE_NAME: "Nakhon Phanom" },
  { PROVINCE_ID: 37, PROVINCE_NAME: "Mukdahan" },
  { PROVINCE_ID: 38, PROVINCE_NAME: "Chiang Mai" },
  { PROVINCE_ID: 39, PROVINCE_NAME: "Lamphun" },
  { PROVINCE_ID: 40, PROVINCE_NAME: "Lampang" },
  { PROVINCE_ID: 41, PROVINCE_NAME: "Uttaradit" },
  { PROVINCE_ID: 42, PROVINCE_NAME: "Phrae" },
  { PROVINCE_ID: 43, PROVINCE_NAME: "Nan" },
  { PROVINCE_ID: 44, PROVINCE_NAME: "Phayao" },
  { PROVINCE_ID: 45, PROVINCE_NAME: "Chiang Rai" },
  { PROVINCE_ID: 46, PROVINCE_NAME: "Mae Hong Son" },
  { PROVINCE_ID: 47, PROVINCE_NAME: "Nakhon Sawan" },
  { PROVINCE_ID: 48, PROVINCE_NAME: "Uthai Thani" },
  { PROVINCE_ID: 49, PROVINCE_NAME: "Kamphaeng Phet" },
  { PROVINCE_ID: 50, PROVINCE_NAME: "Tak" },
  { PROVINCE_ID: 51, PROVINCE_NAME: "Sukhothai" },
  { PROVINCE_ID: 52, PROVINCE_NAME: "Phitsanulok" },
  { PROVINCE_ID: 53, PROVINCE_NAME: "Phichit" },
  { PROVINCE_ID: 54, PROVINCE_NAME: "Phetchabun" },
  { PROVINCE_ID: 55, PROVINCE_NAME: "Ratchaburi" },
  { PROVINCE_ID: 56, PROVINCE_NAME: "Kanchanaburi" },
  { PROVINCE_ID: 57, PROVINCE_NAME: "Suphan Buri" },
  { PROVINCE_ID: 58, PROVINCE_NAME: "Nakhon Pathom" },
  { PROVINCE_ID: 59, PROVINCE_NAME: "Samut Sakhon" },
  { PROVINCE_ID: 60, PROVINCE_NAME: "Samut Songkhram" },
  { PROVINCE_ID: 61, PROVINCE_NAME: "Phetchaburi" },
  { PROVINCE_ID: 62, PROVINCE_NAME: "Prachuap Khiri Khan" },
  { PROVINCE_ID: 63, PROVINCE_NAME: "Nakhon Si Thammarat" },
  { PROVINCE_ID: 64, PROVINCE_NAME: "Krabi" },
  { PROVINCE_ID: 65, PROVINCE_NAME: "Phang Nga" },
  { PROVINCE_ID: 66, PROVINCE_NAME: "Phuket" },
  { PROVINCE_ID: 67, PROVINCE_NAME: "Surat Thani" },
  { PROVINCE_ID: 68, PROVINCE_NAME: "Ranong" },
  { PROVINCE_ID: 69, PROVINCE_NAME: "Chumphon" },
  { PROVINCE_ID: 70, PROVINCE_NAME: "Songkhla" },
  { PROVINCE_ID: 71, PROVINCE_NAME: "Satun" },
  { PROVINCE_ID: 72, PROVINCE_NAME: "Trang" },
  { PROVINCE_ID: 73, PROVINCE_NAME: "Phatthalung" },
  { PROVINCE_ID: 74, PROVINCE_NAME: "Pattani" },
  { PROVINCE_ID: 75, PROVINCE_NAME: "Yala" },
  { PROVINCE_ID: 76, PROVINCE_NAME: "Narathiwat" },
  { PROVINCE_ID: 77, PROVINCE_NAME: "Bueng Kan" },
];
